### PR TITLE
Added local pre commit hook for python formatting

### LINKED ISSUE #7: Add formatting for codestyle compliance
**As a** Developer, **I want** to ensure correctness and readability of my code, **so that** I can maintain the code more easily.

### Acceptance Criteria

If I commit then:
a formatter should run that checks the code and automatically formats it in the correct style so that no unformatted code can be pushed

### PR DESCRIPTION
**Pull request by JoshuaSchlucke**
Resolves #7 

Added a local pre-commit hook that uses yapf-diff to auto format the code before it is committed.

PLEASE TEST ON YOUR LOCAL MACHINE BEFORE ACCEPTING IT!

to test: install pre-commit and then use pre-commit install and autoupdate and then try to commit something
(I'll explain better as soon as I have the time)

### CODE REVIEW

**Comment by JoshuaSchlucke** [comment]
Added the requirements to the setup.py so now you can install all needed requirements with
`pip install cellpose[dev]`
then use:
`pre-commit install`
and all should be set up

**Comment by RenzoRichter** [comment]
Ganzer workflow siehe auch : https://pre-commit.com

**Review by RenzoRichter — APPROVED** [review]
Hey there, great job. 

## MAIN-Review:
All features outlined in the issue are implemented (⇒ code implements issue [#7])

Hook runs through and installation of pre-commit according to [Wki-entry](https://github.com/claassenlab/cellpose/wiki/Formatting-with-yapf) works on my Machine (Windows 11, Pycharm, Conda).

_______________________________________
## Nitpicks

NONE 

______________________________________
### File can be merged to main!

**Review by Davidundso — APPROVED** [review]
Tested pre-commit on Mac, Pycharm. Everything works as described in the wiki, very clear and helpful explanations and a very useful addition for developing. 

I tested:
- Installation on zsh
- changed a file 
- ran pre-commit successfully (file was then correctly formatted)

Good job!

**Pull request merged**
