### PR TITLE
24_on_off_button

### LINKED ISSUE #24: On-off-Button next to each colour button of the sliders
**As a** Cellpose user, **I want** to have a on-off-button next to each colour button of the sliders, **so that** I can turn the button on and off (this will later turn the channel on and off).

### Acceptance Criteria

For example if:
1. I click one of the on-and-off buttons
2. it changes its appearance (so that one can see if it is on or off).

- [x] There are on-off-buttons to the right of the colour buttons of each colour slider.
- [x] The buttons are initialized in the same for-loop as the sliders and the colour buttons for extensibility.
- [x] The button changes its appearance when one clicks it, it has an off-state and an on-state (so that the user can see whether it is on or off).
- [x] The icons used for on and off are publicly availabe and not under any copyright protection.

### Additional Resources:

Bildschirmfoto 2024-06-05 um 16 56 02

Note: In this case Red = ON, Purple = OFF, Yellow = OFF. This is just an illustration of the idea.

### Notes:

The for loop that initializes the sliders can be found in the make_buttons method in the MainW class of the gui. This is the location where each button should be initialized/the method should be called that initializes each button.

### PR DESCRIPTION
**Pull request by robertkrasniqi**
Resolves #24 
Ich habe On-Off-Buttons neben den Farbbuttons der Schieberegler hinzugefügt, um das Ein- und Ausschalten der Kanäle zu ermöglichen.
Die Buttons ändern ihr Aussehen, wenn sie geklickt werden, und haben Zustände für "an" und "aus".
Die Icons für die Zustände "an" und "aus" verwenden die standardmäßigen Qt-Icons media-playback-start und media-playback-stop.

Änderungen:

Hinzufügen einer Liste von On-Off-Buttons (self.on_off_buttons).
Aktualisieren der Methode make_buttons, um die On-Off-Buttons zu erstellen und in die Benutzeroberfläche einzufügen.
Definieren der Methoden create_on_off_button und toggle_on_off.

### CODE REVIEW

**Review by JoshuaSchlucke — APPROVED** [review]
Tested locally and it works well, thanks for documenting your code the docstrings are nice and tidy as well

**Review by Davidundso — COMMENTED** [review]
- Code well understandable, extendable through loop
- tested buttons on Mac, worked as described
- well structured and commented

**Review by sonjajk — APPROVED** [review]
I like your structure and your comments as well and on windows it works as discribed, too.

**Review by ShalinGhe — APPROVED** [review]
Tested the on/off buttons for each marker and it works exactly like it is intended to do. The implementation looks clean and is commented well. It appears to be reasonably extensible, as it utilizes reusable components with a separation of concerns, employs lists to manage buttons for each marker, and integrates the new functionality into the existing layout following a consistent design pattern as the color buttons for each marker. This pull request can be merged.

**Pull request merged**
